package sop_corba.GestionNotificacionesPackage;

/**
* sop_corba/GestionNotificacionesPackage/ClsMensajeNotificacionDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* viernes 5 de agosto de 2022 06:27:32 PM CEST
*/

public final class ClsMensajeNotificacionDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO value = null;

  public ClsMensajeNotificacionDTOHolder ()
  {
  }

  public ClsMensajeNotificacionDTOHolder (sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTOHelper.type ();
  }

}
