package sop_corba.GestionNotificacionesPackage;


/**
* sop_corba/GestionNotificacionesPackage/ClsMensajeNotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* viernes 5 de agosto de 2022 06:27:32 PM CEST
*/

public final class ClsMensajeNotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public double valor = (double)0;
  public String lugar_compra = null;
  public String fecha = null;
  public String medio_pago = null;
  public String nit = null;

  public ClsMensajeNotificacionDTO ()
  {
  } // ctor

  public ClsMensajeNotificacionDTO (double _valor, String _lugar_compra, String _fecha, String _medio_pago, String _nit)
  {
    valor = _valor;
    lugar_compra = _lugar_compra;
    fecha = _fecha;
    medio_pago = _medio_pago;
    nit = _nit;
  } // ctor

} // class ClsMensajeNotificacionDTO
