package sop_corba;


/**
* sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* viernes 5 de agosto de 2022 06:27:32 PM CEST
*/

public interface GestionNotificacionesOperations 
{
  void notificaarRegistro (sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objNotificacion);
} // interface GestionNotificacionesOperations
