package co.edu.unicauca.core.sop_corba;

/**
* sop_corba/GestionNotificacionesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* viernes 5 de agosto de 2022 06:27:32 PM CEST
*/

public final class GestionNotificacionesHolder implements org.omg.CORBA.portable.Streamable
{
  public co.edu.unicauca.core.sop_corba.GestionNotificaciones value = null;

  public GestionNotificacionesHolder ()
  {
  }

  public GestionNotificacionesHolder (co.edu.unicauca.core.sop_corba.GestionNotificaciones initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = co.edu.unicauca.core.sop_corba.GestionNotificacionesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    co.edu.unicauca.core.sop_corba.GestionNotificacionesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return co.edu.unicauca.core.sop_corba.GestionNotificacionesHelper.type ();
  }

}
